### PR TITLE
waiting for table to be ready

### PR DESCRIPTION
**Pull request by amoscatelli**
We were creating the table without waiting for it to be ready.
This caused the table not to be ready and a Resource not found Exception was thrown from aws.
This happens only when using in cloud dynamodb table, I could not reproduce the issue when using the local dynamodb docker instance.

Also adding myself as contributor where I previously contributed.

### CODE REVIEW

**Comment by genie-jnosql** [comment]
Can one of the admins verify this patch?

**Comment by keilw** [comment]
@otaviojava Could you verify that please. It seems Github no longer shows merged PRs under the "contributors" in each repository or is this the first PR by @amoscatelli?

**Comment by otaviojava** [comment]
@amoscatelli thank you for the contribuition

**Comment by keilw** [comment]
Btw not sure, if his membership would allow that at this point, but would you also consider @amoscatelli for a committer election to JNoSQL or is it too soon for that?

**Pull request merged**
