### PR TITLE
DynamoDB Document Driver

### PR DESCRIPTION
**Pull request by amoscatelli**
Hi everybody !
I started working on DynamoDB Document Driver.
I am anticipating the pull request because I have some difficulties/perplexities :

- How can retrieve the ID Column actual name inside the DocumentCollectionManager ?
I expected to be able to access the base java type I have to convert the data from/to to inspect annotations.

I looked at the MongoDB Document Driver and there you always use "_id" constant as id column name.
Isn't this againt the specification ?
In the Document example I see you are supposed to change that.

- Also, won't not being able to access the source java type cause issues in future to properly manage Polymorphism ?
I would expect DocumentConfiguration, DocumentCollectionManagerFactory, DocumentCollectionManager, DocumentEntity to be generic types/interfaces, examples : DocumentConfiguration< Product >, DocumentCollectionManagerFactory< Product >, DocumentCollectionManager< Product >, DocumentEntity< Product > and pass the base type in their methods as a parameter.

- Last but not least, in DocumentCollectionManagerFactory could be usefull to access the base java type also to initialize connection with the nosql database (for example at the moment I am forced to initialize the DynamoDB table inside the DocumentCollectionManager to look for DocumentEntity attributes (aka Documents if I understood correctly). DynamoDB is schema less regarding attributes, but you have to initialize KeySchema regarding the primary key/keys and that can't be changed later.

Thank you id advance.

@otaviojava

### CODE REVIEW

**Comment by genie-jnosql** [comment]
Can one of the admins verify this patch?

**Comment by otaviojava** [comment]
@amoscatelli could you check why it is not working on Java 8?

**Comment by amoscatelli** [comment]
I fixed the issue but this pull request is not ready to be accepted.
To finish the work I need my question answered.

Thank you in advance

**Comment by amoscatelli** [comment]
I closed the pull request for now since I discovered dynamodb allows querying only on indexed columns.
Indexes can be created only at table creation.
Actual jnosql document interfaces don't give me enough informations about Indexes.

**Pull request closed without merging**
